# Site settings
title: "PrestaShop Developers' blog"
email: build@prestashop.com
description: "Official blog for PrestaShop development straight from the product and core dev team."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://build.prestashop.com" # the base hostname & protocol for your site

permalink: /:categories/:title/

paginate: 10
paginate_path: "/page:num/"

google_analytics: "UA-2753771-31"
disqus_shortname: prestashopbuild

twitter_username: PrestaShop
github_username:  PrestaShop
instagram_username: prestashop
spotify_username: prestacrew

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: ["bower.json", "bower_components", "Gemfile", "Gemfile.lock", ".travis.yml", "vendor"]

sass:
  load_paths:
    - _sass
  style: compressed

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-gist
  - jekyll-algolia

algolia:
  application_id: '17LZR6CZEL'
  index_name: 'jekyll'

# Page collection are used for how-tos pages
howtos:
- theme:
  icon: fa-crop
- module:
  icon: fa-lightning
- pdf:
  icon: fa-file
- misc:
  icon: fa-random
- upgrade:
  icon: fa-retweet-1
- translation:
  icon: fa-globe

# Required to use local jekyll server with Chrome
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
