baseURL: https://build.prestashop-project.org
disablePathToLower: true
languageCode: en-us
title: PrestaShop Developers' blog
timezone: Europe/Paris

theme: "build"

enableEmoji: true

mainSections:
  - news

cascade:
  # default social image
  twitter_image: "/assets/images/theme/meta-logo-build.png"

permalinks:
  news: /news/:year/:slugorfilename/
  tags: /tag/:slug/

googleAnalytics: "G-QVW3BYSGJJ"
disqusShortname: prestashopbuild

params:
  email: build@prestashop.com
  # algolia search settings
  algolia:
    application_id: '17LZR6CZEL'
    index_name: 'blog'

social:
  twitter: "PrestaShopOrg"
  github: "PrestaShop"

mediaTypes:
  application/ndjson:
    suffixes: ['ndjson']

rssLimit: 15

outputFormats:
  # rss feed generation
  RSS:
    mediaType: application/rss+xml
    basename: feed
  # algolia index generation
  algolia:
    baseName: "algolia"
    isPlainText: true
    mediaType: "application/ndjson"
    notAlternative: true

outputs:
  home:
    ["HTML", "RSS", "algolia"]

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    style: github
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 1
